<?xml version="1.0" encoding="UTF-8" standalone="yes"?>


<!DOCTYPE Biblioteca [
    <!ELEMENT Biblioteca (libros,revistas,periodicos)>
    <!ELEMENT libros (libro+)>
    <!ATTLIST libros tipo_libros CDATA #REQUIRED>
    <!ELEMENT revistas (revista+)>
    <!ATTLIST revistas tipo_revistas CDATA #REQUIRED>
    <!ELEMENT periodicos (periodico+)>
    <!ELEMENT libro (titulo_libro,capitulos,indice_libro,sinopsis)>
    <!ATTLIST libro id ID #REQUIRED>
    <!ATTLIST libro tipo_clase CDATA #REQUIRED>
    <!ATTLIST libro num_paginas CDATA #REQUIRED>
    <!ELEMENT titulo_libro (#PCDATA)>
    <!ELEMENT capitulos (capitulo+)>
    <!ATTLIST capitulo num_paginas CDATA #REQUIRED>
    <!ELEMENT capitulo (titulo_capitulo,contenido_libro)>
    <!ELEMENT titulo_capitulo (#PCDATA)>
    <!ELEMENT contenido_libro (#PCDATA)>
    <!ATTLIST contenido_libro enlace CDATA #REQUIRED>
    <!ELEMENT indice_libro (#PCDATA)>
    <!ELEMENT sinopsis (#PCDATA)>
    <!ELEMENT revista (titulo_revista,indice_revista,secciones_revista)>
    <!ATTLIST revista id ID #REQUIRED>
    <!ATTLIST revista tipo_clase CDATA #REQUIRED>
    <!ATTLIST revista num_paginas CDATA #REQUIRED>
    <!ELEMENT titulo_revista (#PCDATA)>
    <!ELEMENT indice_revista (#PCDATA)>
    <!ELEMENT secciones_revista (seccion_revista+)>
    <!ATTLIST seccion_revista num_paginas CDATA #REQUIRED>
    <!ELEMENT seccion_revista (contenido_revista+)>
    <!ELEMENT contenido_revista (#PCDATA)>
    <!ATTLIST contenido_revista enlace CDATA #REQUIRED>
    <!ELEMENT periodico (secciones_periodico,indice)>
    <!ATTLIST periodico id ID #REQUIRED>
    <!ATTLIST periodico tipo_periodico (nacional|internacional) #IMPLIED>
    <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
    <!ELEMENT secciones_periodico (seccion_periodico+)>
    <!ELEMENT seccion_periodico (articulo+)>
    <!ATTLIST seccion_periodico tipo_seccion (economia|opinion|deportes|nacional|internacional) #IMPLIED>
    <!ELEMENT articulo (contenido_periodico)>
    <!ELEMENT contenido_periodico (#PCDATA)>
    <!ATTLIST articulo autor CDATA #REQUIRED>
    <!ATTLIST contenido_periodico enlace CDATA #REQUIRED>
    <!ELEMENT indice (#PCDATA)>
]>

<Biblioteca>

    <!-- LIBROS -->

    <!-- Cada libro puede clasificarse en tipo_clase: novela, infantil o didactico-->
    <libros tipo_libros="novela|infantil|didactico">
        <libro id="L0001" tipo_clase="novela" num_paginas="198">
            <titulo_libro>Demian</titulo_libro>
            <capitulos>
                <capitulo num_paginas="21">
                    <titulo_capitulo>El pajaro rompe el cascaron</titulo_capitulo>
                    <contenido_libro enlace="http://bibliotecadigital.ilce.edu.mx/Colecciones/ObrasClasicas/_docs/Demian_HermannHesse.pdf"></contenido_libro>
                </capitulo>
            </capitulos>
            <indice_libro>
                1.Los dos mundos....................2 
                2.Caín.............................25 
                3.El mal Ladrón....................48 
                4.Beatrice.........................72 
                5.El pajaro rompe el cascaron......97
                6.La lucha de Jacob...............118 
                7.Frau eva........................143 
                8.El principio del fin............172     
            </indice_libro>
            <sinopsis>Demian es la historia de Emil Sinclair. La historia de un niño que ve, más allá de los algodones que envuelven su vida familiar, el otro mundo que le rodea: un mundo que teme pero a la vez le fascina
            En definitiva, la búsqueda de nuestro auténtico yo a través del rechazo de lo preestablecido.
            </sinopsis>
        </libro>
    </libros>
    <!-- REVISTAS -->

    <!--  Cada revista puede clasificarse en tipo_clase: informatica, corazon, coches, investigacion u otras.-->
    <revistas tipo_revistas="informatica|corazon|coches|investigacion|otras">
        <revista id="R0001" tipo_clase="investigacion" num_paginas="68">
            <titulo_revista>Muy Interesante</titulo_revista>
            <indice_revista>
                1.La verdad sobre el coronavirus.....................2 
                2.Embrujo cuántico...................................6 
                3.El verdadero poder de la epigenética...............9
                4.500 años de la revuelta comunera..................13
                5.SOS: el desastre de los desiertos marinos.........16
                6.La convivencia entre coches  listos y coches......19 
                7.Aventura espacial made in Spain...................22 
                8.Literatura erótica................................26 
                9.Crónicas del futuro: un robot entre el centeno....32
            </indice_revista>
            <secciones_revista>
                <seccion_revista num_paginas="5">
                    <contenido_revista enlace="https://www.muyinteresante.es/revista-muy/noticias-muy/articulo/la-verdad-del-coronavirus-en-la-nueva-revista-muy-interesante-581584706205"></contenido_revista>
                </seccion_revista>
            </secciones_revista>
        </revista>
    </revistas>
    <!-- PERIODICOS -->

    <!-- Cada seccion puede ser tipo: economia, opinion, deportes, nacional o internacional.-->
    <periodicos>
        <periodico id="P0001" tipo_periodico="nacional" fecha_publicacion="16 de mayo de 2021">
            <secciones_periodico>
                <seccion_periodico tipo_seccion="deportes">
                    <articulo autor="Jorge Noguera">
                        <contenido_periodico enlace="https://as.com/tenis/?omnil=mpal">Rafa Nadal es el nuevo campeón del Masters 1.000 de Roma 2021 y, como tal, le corresponde el cheque más jugoso de un montante total de premios en metálico que esta edición asciende a 2.082.960 euros, un 39,9%menos que en la anterior.

                        De esa cifra, Nadal se lleva 245.085 euros, un 19,4% más que Djokovic, campeón el año pasado. Al serbio le corresponden, como finalista, 145.000 euros, un 3,3% menos que Schwartzman en 2020. Roberto Bautista, que alcanzó los octacvos, se lleva por su parte 28.200 euros, un recorte del 53,77% respecto a la edición precedente. El mismo que sufre Davidovich, otro que alcanzó la tercera ronda.</contenido_periodico>
                    </articulo>
                </seccion_periodico>
            </secciones_periodico>
            <indice>
                1.Futbol..................2
                2.Motor...................8
                3.Baloncesto.............12
                4.Tenis..................16
                5.Ciclismo...............19
                6.Más deporte............22
                7.Opinion................26
            </indice>
        </periodico>
    </periodicos>

</Biblioteca>